apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: khoolview
  namespace: khoolsession
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: khoolview
subjects:
- kind: ServiceAccount
  name: khoolsa
  namespace: khoolsession